version: "3.7"

services:
  api:
    container_name: rhythm-node
    restart: always
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src/
      - ./uploads:/app/uploads/
    ports:
      - 3011:3011
