version: "3.7"

services:
  rhythm-db:
    container_name: rhythm-db
    image: mysql
    restart: always
    environment:
      - MYSQL_PASSWORD=Rhyt#m@12345
      - MYSQL_ROOT_PASSWORD=Rhyt#m@12345
      - MYSQL_DATABASE=rhythm
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306
  api:
    container_name: rhythm-node
    restart: always
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src/
      - ./uploads:/app/uploads/
    ports:
      - 3011:3011
    depends_on:
      - rhythm-db
    links:
      - rhythm-db

volumes:
  db-config:
  db-data:
